// <auto-generated />
namespace Gym.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add2tables32 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add2tables32));
        
        string IMigrationMetadata.Id
        {
            get { return "201612191651402_add2tables32"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
