// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject2
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinPane uIIndexMyASPNETApplicaPane = this.UIIndexMyASPNETApplicaWindow.UIIndexMyASPNETApplicaPane;
            WinPane uIRegisterRoleMyASPNETPane = this.UIIndexMyASPNETApplicaWindow.UIRegisterRoleMyASPNETPane;
            WinPane uIItemPane = this.UIItemWindow.UIItemPane;
            #endregion

            // Click 'Index - My ASP.NET Application - Google Chrome' pane
            Mouse.Click(uIIndexMyASPNETApplicaPane, new Point(838, 120));

            // Click 'Index - My ASP.NET Application - Google Chrome' pane
            Mouse.Click(uIIndexMyASPNETApplicaPane, new Point(577, 215));

            // Click 'RegisterRole - My ASP.NET Application - Google Chr...' pane
            Mouse.Click(uIRegisterRoleMyASPNETPane, new Point(627, 315));

            // Click pane
            Mouse.Click(uIItemPane, new Point(33, 25));

            // Click 'RegisterRole - My ASP.NET Application - Google Chr...' pane
            Mouse.Click(uIRegisterRoleMyASPNETPane, new Point(622, 360));
        }
        
        /// <summary>
        /// RecordedMethod2 - Use 'RecordedMethod2Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            WinPane uIIndexMyASPNETApplicaPane = this.UIIndexMyASPNETApplicaWindow.UIIndexMyASPNETApplicaPane;
            WinPane uICreateMyASPNETApplicPane = this.UIIndexMyASPNETApplicaWindow.UICreateMyASPNETApplicPane;
            WinMenu uIAutouzupełnianieMenu = this.UIItemWindow1.UIItemClient.UIAutouzupełnianieMenu;
            WinControl uICreateMyASPNETApplicDocument = this.UIIndexMyASPNETApplicaWindow.UIChromeLegacyWindowWindow.UICreateMyASPNETApplicDocument;
            #endregion

            // Click 'Index - My ASP.NET Application - Google Chrome' pane
            Mouse.Click(uIIndexMyASPNETApplicaPane, new Point(895, 109));

            // Click 'Index - My ASP.NET Application - Google Chrome' pane
            Mouse.Click(uIIndexMyASPNETApplicaPane, new Point(457, 209));

            // Click 'Create - My ASP.NET Application - Google Chrome' pane
            Mouse.Click(uICreateMyASPNETApplicPane, new Point(606, 277));

            // Type 'title{Tab}' in 'Autouzupełnianie' popup menu
            Keyboard.SendKeys(uIAutouzupełnianieMenu, this.RecordedMethod2Params.UIAutouzupełnianieMenuSendKeys, ModifierKeys.None);

            // Type 'd' in 'Create - My ASP.NET Application - Google Chrome' document
            Keyboard.SendKeys(uICreateMyASPNETApplicDocument, this.RecordedMethod2Params.UICreateMyASPNETApplicDocumentSendKeys, ModifierKeys.None);

            // Type 'esci' in 'Autouzupełnianie' popup menu
            Keyboard.SendKeys(uIAutouzupełnianieMenu, this.RecordedMethod2Params.UIAutouzupełnianieMenuSendKeys1, ModifierKeys.None);

            // Type '{Back}' in 'Create - My ASP.NET Application - Google Chrome' document
            Keyboard.SendKeys(uICreateMyASPNETApplicDocument, this.RecordedMethod2Params.UICreateMyASPNETApplicDocumentSendKeys1, ModifierKeys.None);

            // Type 'r' in 'Autouzupełnianie' popup menu
            Keyboard.SendKeys(uIAutouzupełnianieMenu, this.RecordedMethod2Params.UIAutouzupełnianieMenuSendKeys2, ModifierKeys.None);

            // Type 'iption' in 'Create - My ASP.NET Application - Google Chrome' document
            Keyboard.SendKeys(uICreateMyASPNETApplicDocument, this.RecordedMethod2Params.UICreateMyASPNETApplicDocumentSendKeys2, ModifierKeys.None);

            // Click 'Create - My ASP.NET Application - Google Chrome' pane
            Mouse.Click(uICreateMyASPNETApplicPane, new Point(627, 374));
        }
        
        #region Properties
        public virtual RecordedMethod2Params RecordedMethod2Params
        {
            get
            {
                if ((this.mRecordedMethod2Params == null))
                {
                    this.mRecordedMethod2Params = new RecordedMethod2Params();
                }
                return this.mRecordedMethod2Params;
            }
        }
        
        public UIIndexMyASPNETApplicaWindow UIIndexMyASPNETApplicaWindow
        {
            get
            {
                if ((this.mUIIndexMyASPNETApplicaWindow == null))
                {
                    this.mUIIndexMyASPNETApplicaWindow = new UIIndexMyASPNETApplicaWindow();
                }
                return this.mUIIndexMyASPNETApplicaWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1();
                }
                return this.mUIItemWindow1;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod2Params mRecordedMethod2Params;
        
        private UIIndexMyASPNETApplicaWindow mUIIndexMyASPNETApplicaWindow;
        
        private UIItemWindow mUIItemWindow;
        
        private UIItemWindow1 mUIItemWindow1;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class RecordedMethod2Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'title{Tab}' in 'Autouzupełnianie' popup menu
        /// </summary>
        public string UIAutouzupełnianieMenuSendKeys = "title{Tab}";
        
        /// <summary>
        /// Type 'd' in 'Create - My ASP.NET Application - Google Chrome' document
        /// </summary>
        public string UICreateMyASPNETApplicDocumentSendKeys = "d";
        
        /// <summary>
        /// Type 'esci' in 'Autouzupełnianie' popup menu
        /// </summary>
        public string UIAutouzupełnianieMenuSendKeys1 = "esci";
        
        /// <summary>
        /// Type '{Back}' in 'Create - My ASP.NET Application - Google Chrome' document
        /// </summary>
        public string UICreateMyASPNETApplicDocumentSendKeys1 = "{Back}";
        
        /// <summary>
        /// Type 'r' in 'Autouzupełnianie' popup menu
        /// </summary>
        public string UIAutouzupełnianieMenuSendKeys2 = "r";
        
        /// <summary>
        /// Type 'iption' in 'Create - My ASP.NET Application - Google Chrome' document
        /// </summary>
        public string UICreateMyASPNETApplicDocumentSendKeys2 = "iption";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIIndexMyASPNETApplicaWindow : WinWindow
    {
        
        public UIIndexMyASPNETApplicaWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Index - My ASP.NET Application - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Index - My ASP.NET Application - Google Chrome");
            this.WindowTitles.Add("RegisterRole - My ASP.NET Application - Google Chrome");
            this.WindowTitles.Add("Create - My ASP.NET Application - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinPane UIIndexMyASPNETApplicaPane
        {
            get
            {
                if ((this.mUIIndexMyASPNETApplicaPane == null))
                {
                    this.mUIIndexMyASPNETApplicaPane = new WinPane(this);
                    #region Search Criteria
                    this.mUIIndexMyASPNETApplicaPane.SearchProperties[WinControl.PropertyNames.Name] = "Index - My ASP.NET Application - Google Chrome";
                    this.mUIIndexMyASPNETApplicaPane.WindowTitles.Add("Index - My ASP.NET Application - Google Chrome");
                    #endregion
                }
                return this.mUIIndexMyASPNETApplicaPane;
            }
        }
        
        public WinPane UIRegisterRoleMyASPNETPane
        {
            get
            {
                if ((this.mUIRegisterRoleMyASPNETPane == null))
                {
                    this.mUIRegisterRoleMyASPNETPane = new WinPane(this);
                    #region Search Criteria
                    this.mUIRegisterRoleMyASPNETPane.SearchProperties[WinControl.PropertyNames.Name] = "RegisterRole - My ASP.NET Application - Google Chrome";
                    this.mUIRegisterRoleMyASPNETPane.WindowTitles.Add("RegisterRole - My ASP.NET Application - Google Chrome");
                    #endregion
                }
                return this.mUIRegisterRoleMyASPNETPane;
            }
        }
        
        public WinPane UICreateMyASPNETApplicPane
        {
            get
            {
                if ((this.mUICreateMyASPNETApplicPane == null))
                {
                    this.mUICreateMyASPNETApplicPane = new WinPane(this);
                    #region Search Criteria
                    this.mUICreateMyASPNETApplicPane.SearchProperties[WinControl.PropertyNames.Name] = "Create - My ASP.NET Application - Google Chrome";
                    this.mUICreateMyASPNETApplicPane.WindowTitles.Add("Create - My ASP.NET Application - Google Chrome");
                    #endregion
                }
                return this.mUICreateMyASPNETApplicPane;
            }
        }
        
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinPane mUIIndexMyASPNETApplicaPane;
        
        private WinPane mUIRegisterRoleMyASPNETPane;
        
        private WinPane mUICreateMyASPNETApplicPane;
        
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Chrome Legacy Window";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_RenderWidgetHostHWND";
            this.WindowTitles.Add("Create - My ASP.NET Application - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UICreateMyASPNETApplicDocument
        {
            get
            {
                if ((this.mUICreateMyASPNETApplicDocument == null))
                {
                    this.mUICreateMyASPNETApplicDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUICreateMyASPNETApplicDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUICreateMyASPNETApplicDocument.WindowTitles.Add("Create - My ASP.NET Application - Google Chrome");
                    #endregion
                }
                return this.mUICreateMyASPNETApplicDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUICreateMyASPNETApplicDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Pulpit 1";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            #endregion
        }
        
        #region Properties
        public WinPane UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new WinPane(this);
                }
                return this.mUIItemPane;
            }
        }
        #endregion
        
        #region Fields
        private WinPane mUIItemPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            #endregion
        }
        
        #region Properties
        public UIItemClient UIItemClient
        {
            get
            {
                if ((this.mUIItemClient == null))
                {
                    this.mUIItemClient = new UIItemClient(this);
                }
                return this.mUIItemClient;
            }
        }
        #endregion
        
        #region Fields
        private UIItemClient mUIItemClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemClient : WinClient
    {
        
        public UIItemClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
        }
        
        #region Properties
        public WinMenu UIAutouzupełnianieMenu
        {
            get
            {
                if ((this.mUIAutouzupełnianieMenu == null))
                {
                    this.mUIAutouzupełnianieMenu = new WinMenu(this);
                    #region Search Criteria
                    this.mUIAutouzupełnianieMenu.SearchProperties[WinMenu.PropertyNames.Name] = "Autouzupełnianie";
                    #endregion
                }
                return this.mUIAutouzupełnianieMenu;
            }
        }
        #endregion
        
        #region Fields
        private WinMenu mUIAutouzupełnianieMenu;
        #endregion
    }
}
